# Generated by Django 4.2.16 on 2024-12-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('quarter', models.PositiveIntegerField(choices=[(1, '1 четверть'), (2, '2 четверть'), (3, '3 четверть'), (4, '4 четверть')], verbose_name='Четверть')),
                ('score', models.PositiveIntegerField(verbose_name='Оценка')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата оценки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_grades', to='general.studentprofile', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_grades', to='general.teacherprofile', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Четвертная оценка',
                'verbose_name_plural': 'Четвертные оценки',
                'ordering': ['student', 'subject', 'quarter'],
            },
        ),
    ]
